### ISSUE TITLE
Clicking on map for USA Spy Satellite work Wrong + Skirmish Menu need your Attention

### ISSUE THREAD

**Issue by PAPIONbit** [xezon/GeneralsControlBar#1]
Hi
Thanks for the great work.

#### Expectation:
When i **left click** on ControlBar Pro map while i using USA Spy Satellite, It just show there.

#### Actual behavior:
It act like i am **right-clicking** there and just move the map there.
___
+ I ask you please modify the skirmish game menu bar too.

v1.1

Best regards

**Comment by xezon** [comment]
Hi. I do not understand. Can you please post image to clarify?
